### ISSUE TITLE
Group stage predictions does not work

### ISSUE THREAD

**Issue by fabiogrillo** [ifrankandrade/fifa-world-cup-2022-prediction#2]
Hello @ifrankandrade , wonderful work of yours! I'm learning a lot but i noticed that once I get to the group stage prediction part, something goes wrong and I had this kind of error: 

> "TypeError: can only concatenate str (not "float") to str"

 from ` dict_table[group].loc[dict_table[group]['Team'] == home, 'Pts'] += points_home`. 

I tried but i can't undestand what's wrong

**Comment by daniels13ca** [comment]
A simple solution is to set all values to 0 in the pickle file creation (Step 1):

`all_tables = pd.read_html('https://en.wikipedia.org/wiki/2022_FIFA_World_Cup')`
`dict_table = {}`
`for letter, i in zip(alphabet, range(13,69,7)): # A=13, B=20, ...`
 `   df = all_tables[i]`
 `   df.rename(columns={df.columns[1]:'Team'}, inplace=True)`
 `   #Add this line:`
 `   df[['Pld', 'W', 'D', 'L', 'GF', 'GA', 'GD', 'Pts']] = 0`
 `   df.pop('Qualification')`
`    dict_table[f'Group {letter}'] = df`

This is because the tables in website are updated after every match

**Comment by fabiogrillo** [comment]
Thanks a lot @daniels13ca !
